### ISSUE TITLE
Invalid entrypoint in latest container release for c7n-org

### ISSUE THREAD

**Issue by brandocorp** [cloud-custodian/cloud-custodian#10269]
### Describe the bug

When running the latest container release for `cloudcustodian/c7n-org`, we receive an error saying 

Failing image: `sha256:c04370b987313412d783a1ef0a241302380e4579621b966bed6f99333fd54871` 
```sh
$ docker run --rm -it cloudcustodian/c7n-org bash
Unable to find image 'cloudcustodian/c7n-org:latest' locally
latest: Pulling from cloudcustodian/c7n-org
e3bd89a9dac5: Pull complete
2416012f448b: Pull complete
ffe506b0fed1: Pull complete
4f4fb700ef54: Pull complete
ced5c01ee4af: Pull complete
59d7baefb015: Pull complete
Digest: sha256:c04370b987313412d783a1ef0a241302380e4579621b966bed6f99333fd54871
Status: Downloaded newer image for cloudcustodian/c7n-org:latest
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/c7n-org": stat /usr/local/bin/c7n-org: no such file or directory: unknown.
```

It looks like the `entrypoint` is maybe not copied or linked in the expected location.

```
$ docker run --entrypoint /usr/bin/bash --rm -it cloudcustodian/c7n-org:latest
custodian@2fb21a0f893d:~$ which c7n-org
custodian@2fb21a0f893d:~$ cd /usr/bin/
Display all 308 possibilities? (y or n)
custodian@2fb21a0f893d:~$ find / -name c7n-org
find: ‘/root’: Permission denied
find: ‘/home/ubuntu’: Permission denied
find: ‘/var/cache/ldconfig’: Permission denied
find: ‘/proc/tty/driver’: Permission denied
find: ‘/etc/ssl/private’: Permission denied
/src/.venv/bin/c7n-org
```

### What did you expect to happen?

Using an older image sha, we do not see the same error

```sh
$ docker pull cloudcustodian/c7n-org@sha256:eed1dec712b721db65256e6161a8c83984ddf4f1688eae0bdc1e15e0a3edc3c3
docker.io/cloudcustodian/c7n-org@sha256:eed1dec712b721db65256e6161a8c83984ddf4f1688eae0bdc1e15e0a3edc3c3: Pulling from cloudcustodian/c7n-org
2f074dc76c5d: Pull complete
25394419bc01: Pull complete
4861087fd4c0: Pull complete
41c0a644b44d: Pull complete
d81a20df74b9: Pull complete
7434735a8c4d: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:eed1dec712b721db65256e6161a8c83984ddf4f1688eae0bdc1e15e0a3edc3c3
Status: Downloaded newer image for cloudcustodian/c7n-org@sha256:eed1dec712b721db65256e6161a8c83984ddf4f1688eae0bdc1e15e0a3edc3c3
docker.io/cloudcustodian/c7n-org@sha256:eed1dec712b721db65256e6161a8c83984ddf4f1688eae0bdc1e15e0a3edc3c3

$ docker run --rm -it cloudcustodian/c7n-org@sha256:eed1dec712b721db65256e6161a8c83984ddf4f1688eae0bdc1e15e0a3edc3c3
Usage: c7n-org [OPTIONS] COMMAND [ARGS]...

  custodian organization multi-account runner.

Options:
  --help  Show this message and exit.

Commands:
  report      report on a cross account policy execution.
  run         run a custodian policy across accounts
  run-script  run an aws/azure/gcp script across accounts
```

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell

```

### Policy

```shell

```

### Relevant log/traceback output

```shell

```

**Comment by kapilt** [comment]
Ack, thanks, we switched out packaging this past release to uv, and the c7n docker image is part of tests but we should add a c7n-org test.

I would recommend pinning to the last release instead of latest if viable 0.9.45

**Comment by pkeecom** [comment]
Sorry @kapilt - Surely you need to fix it by releasing an urgent patch? It is clearly broken. When is it coming? (0.9.45.1)

**Comment by kapilt** [comment]
ack, there is a pr to fix, and the last release can be used or alternatively the nightly once the fix is merged. the community meeting is tomorrow wrt to discussion about a separate release for it.

**Comment by matthew-foreman** [comment]
Apparently this is still not fixed, or perhaps the error has cropped up again. We are getting the same error when using latest. The pr linked above has been approved and tests passed. Does someone just have to click merge?
