### ISSUE TITLE
Slack Lambda Function Error

### ISSUE THREAD

**Issue by RecursiveLooper1992** [cloud-custodian/cloud-custodian#2324]
Hello,

First of all this is an awesome tool, and we love it!
We noticed you recently added Slack Integration for c7n-mailer.
As we were excited to see this, we gave it a try and ran into the following issue:

```
MailerSqsQueueProcessor(). 
Error: No module named requests 

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 126, in run
self.process_sqs_message(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 170, in process_sqs_message
from .slack_delivery import SlackDelivery
File "/var/task/c7n_mailer/slack_delivery.py", line 17, in <module>
import requests
ImportError: No module named requests
```
It appears that the Lambda Function is unable to pull in the ```requests``` module in the Deployment Package. We are not able to see the Lambda code, as it is too large to view in the Lambda Editor. 

We appreciate the help!

**Comment by RecursiveLooper1992** [comment]
Thank you for the update.

We pulled the latest from trunk and re-ran.
We are still experiencing the following issue in the Lambda Function:

```
MailerSqsQueueProcessor(). 
Error: No module named urllib3 

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 126, in run
self.process_sqs_message(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 170, in process_sqs_message
from .slack_delivery import SlackDelivery
File "/var/task/c7n_mailer/slack_delivery.py", line 17, in <module>
import requests
File "/var/task/requests/__init__.py", line 43, in <module>
import urllib3
ImportError: No module named urllib3
```

Let me know if I can provide any more information, we appreciate the help!

**Comment by LykinsN** [comment]
I've opened a PR to refactor the Slack code so SlackClient is no longer required, and it now points to the Boto implementation of the requests library.

https://github.com/capitalone/cloud-custodian/pull/2341

**Comment by kapilt** [comment]
I've merged #2333 which attempts to resolves this as a drive by. While #2341 helps slim the lambda size by removing extraneous deps, it doesn't fully address the dependency packaging issues. #2333 pulls in the full recursive dependency set for the mailer, and pickups several non python files in the dependency tree (certifi pkg pem files).

@RecursiveLooper1992 please give trunk another try.

**Comment by RecursiveLooper1992** [comment]
Thank you for taking a look into this.

We are closer to solving the problem, but are still seeing the following error:
```
SSLError: [Errno 2] No such file or directory
```

Thanks again for your help!

**Comment by LykinsN** [comment]
Can you post the full trace, that shows which item is missing?

**Comment by LykinsN** [comment]
There might be an issue with the revised lambda dependencies; can you confirm against a test branch in which I've reverted these changes? It includes that change as well as a consolidation of the recent Slack development work.

https://github.com/LykinsN/cloud-custodian/tree/mailer-test

**Comment by tanzwud** [comment]
We have the same problem with the latest mailer for some reason.

`Error starting mailer MailerSqsQueueProcessor(). 
 Error: No module named urllib3 

Traceback (most recent call last):
  File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
    mailer_sqs_queue_processor.run(parallel)
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 128, in run
    self.process_sqs_message(sqs_message)
  File "/var/task/c7n_mailer/sqs_queue_processor.py", line 173, in process_sqs_message
    from .slack_delivery import SlackDelivery
  File "/var/task/c7n_mailer/slack_delivery.py", line 16, in <module>
    import requests
  File "/var/task/requests/__init__.py", line 43, in <module>
    import urllib3
ImportError: No module named urllib3`
