### ISSUE TITLE
Failed to match AWS access key when user have multiple keys

### ISSUE THREAD

**Issue by yufuluo** [cloud-custodian/cloud-custodian#5583]
**Describe the bug**
We have some users that have 2 pairs of active keys, and we would like to only disable the keys that have never been used AND are created in x days. There's a user with 2 keys both created in x days, but one has been used and the other has not. 
The order of the filters seems to affect the result. Both of the keys are disabled by Cloud Custodian with the following policy:
```
  - name: iam-user-never-used-key
    resource: iam-user
    filters:
      - not:
          - "tag:Custodian": whitelist
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_used_date
        value: absent
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 3
        op: lte
    actions:
      - type: remove-keys
        matched: true
        disable: true
```
and the `resource.json` is as follows:
```
[
  {
    "Path": "/",
    "UserName": "<username>",
    "UserId": "<UserId>",
    "Arn": "arn:aws:iam::<accountid>:user/<username>",
    "CreateDate": "2020-04-10T04:07:06+00:00",
    "Tags": [
      {
        "Key": "Cloud-custodian ",
        "Value": "test"
      }
    ],
    "c7n:matched-keys": [
      {
        "active": true,
        "last_rotated": "2020-04-10T17:52:29+00:00",
        "last_used_date": null,
        "last_used_region": null,
        "last_used_service": null,
        "c7n:match-type": "credential"
      },
      {
        "active": true,
        "last_rotated": "2020-04-10T04:07:09+00:00",
        "last_used_date": "2020-04-10T04:10:00+00:00",
        "last_used_region": "us-west-2",
        "last_used_service": "ec2",
        "c7n:match-type": "credential"
      }
    ],
    "c7n:credential-report": {
      "user": "<username>",
      "arn": "arn:aws:iam::<accountid>:user/<username>",
      "user_creation_time": "2020-04-10T04:07:06+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-04-10T17:52:29+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        },
        {
          "active": true,
          "last_rotated": "2020-04-10T04:07:09+00:00",
          "last_used_date": "2020-04-10T04:10:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "ec2",
          "c7n:match-type": "credential"
        }
      ]
    }
  }
]
```
----
If I change the order of the filters to search for never-used-keys as the last one, it's working as expected:
```
  - name: iam-user-never-used-key
    resource: iam-user
    filters:
      - not:
          - "tag:Custodian": whitelist
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 3
        op: lte
      - type: credential
        key: access_keys.last_used_date
        value: absent
    actions:
      - type: remove-keys
        matched: true
        disable: true
```
and result:
```
[
  {
    "Path": "/",
    "UserName": "<username>",
    "UserId": "<UserId>",
    "Arn": "arn:aws:iam::<accountid>:user/<username>",
    "CreateDate": "2020-04-10T04:07:06+00:00",
    "Tags": [
      {
        "Key": "Cloud-custodian ",
        "Value": "test"
      }
    ],
    "c7n:matched-keys": [
      {
        "active": true,
        "last_rotated": "2020-04-10T17:52:29+00:00",
        "last_used_date": null,
        "last_used_region": null,
        "last_used_service": null,
        "c7n:match-type": "credential"
      }
    ],
    "c7n:credential-report": {
      "user": "<username>",
      "arn": "arn:aws:iam::<accountid>:user/<username>",
      "user_creation_time": "2020-04-10T04:07:06+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-04-10T17:52:29+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        },
        {
          "active": true,
          "last_rotated": "2020-04-10T04:07:09+00:00",
          "last_used_date": "2020-04-10T04:10:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "ec2"
        }
      ]
    }
  }
]
```

**Background (please complete the following information):**
 - c7n version: 0.8.45.4

**Comment by kapilt** [comment]
this has been addressed already on trunk in #5551

**Comment by yufuluo** [comment]
No this had not been fixed by #5551. 
I've updated my local source code with change on #5551, yet with the following policy, it gets the key that does not meet the filter:
```
  - name: iam-user-never-used-key
    resource: iam-user
    filters:
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 90
        op: gte
      - type: credential
        key: access_keys.last_used_date
        value: absent
    actions:
      - type: remove-keys
        matched: true
        disable: true
```
The key it catches is newly created, and not older then 90 days:
```
{
    "Path": "/",
    "UserName": "user1",
    "UserId": "xxxxxxx",
    "Arn": "arn:aws:iam::accountid:user/user1",
    "CreateDate": "2014-01-15T19:57:30+00:00",
    "c7n:matched-keys": [
      {
        "active": true,
        "last_rotated": "2020-04-09T17:35:30+00:00",
        "last_used_date": null,
        "last_used_region": null,
        "last_used_service": null,
        "c7n:match-type": "credential"
      }
    ],
    "c7n:credential-report": {
      "user": "user1",
      "arn": "arn:aws:iam::accountid:user/user1",
      "user_creation_time": "2014-01-15T19:57:30+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-04-09T17:35:30+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        }
```

**Comment by yufuluo** [comment]
And if I changed the filter order, it acts differently (and worse)
```
  - name: iam-user-never-used-key
    resource: iam-user
    filters:
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_used_date
        value: absent
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 90
        op: gte
    actions:
      - type: remove-keys
        matched: true
        disable: true
```
It detected more keys that does not fit the requirements:
```
[
  {
    "Path": "/",
    "UserName": "user3",
    "UserId": "xxxxxxx",
    "Arn": "arn:aws:iam::accountid:user/user3",
    "CreateDate": "2018-12-17T17:50:00+00:00",
    "PasswordLastUsed": "2020-04-10T13:29:15+00:00",
    "c7n:matched-keys": [
      {
        "active": false,
        "last_rotated": "2018-12-17T17:50:01+00:00",
        "last_used_date": null,
        "last_used_region": null,
        "last_used_service": null,
        "c7n:match-type": "credential"
      },
      {
        "active": true,
        "last_rotated": "2019-01-31T23:17:36+00:00",
        "last_used_date": "2020-03-18T17:31:00+00:00",
        "last_used_region": "us-west-2",
        "last_used_service": "ec2",
        "c7n:match-type": "credential"
      }
    ],
    "c7n:credential-report": {
      "user": "user3",
      "arn": "arn:aws:iam::accountid:user/user3",
      "user_creation_time": "2018-12-17T17:50:00+00:00",
      "password_enabled": true,
      "password_last_used": "2020-04-10T13:29:15+00:00",
      "password_last_changed": "2018-12-18T18:18:37+00:00",
      "password_next_rotation": null,
      "mfa_active": true,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2019-01-31T23:17:36+00:00",
          "last_used_date": "2020-03-18T17:31:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "ec2",
          "c7n:match-type": "credential"
        },
        {
          "active": false,
          "last_rotated": "2018-12-17T17:50:01+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        }
      ]
    }
  },
  {
    "Path": "/",
    "UserName": "user2",
    "UserId": "xxxxxx",
    "Arn": "arn:aws:iam::accountid:user/user2",
    "CreateDate": "2019-03-07T20:05:58+00:00",
    "PasswordLastUsed": "2020-04-10T12:16:46+00:00",
    "c7n:matched-keys": [
      {
        "active": false,
        "last_rotated": "2019-03-07T20:05:59+00:00",
        "last_used_date": null,
        "last_used_region": null,
        "last_used_service": null,
        "c7n:match-type": "credential"
      }
    ],
    "c7n:credential-report": {
      "user": "user2",
      "arn": "arn:aws:iam::accountid:user/user2",
      "user_creation_time": "2019-03-07T20:05:58+00:00",
      "password_enabled": true,
      "password_last_used": "2020-04-10T12:16:46+00:00",
      "password_last_changed": "2020-01-29T17:47:45+00:00",
      "password_next_rotation": null,
      "mfa_active": true,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-01-29T17:56:27+00:00",
          "last_used_date": "2020-02-03T20:05:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "rds"
        },
        {
          "active": false,
          "last_rotated": "2019-03-07T20:05:59+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        }
      ]
    }
  },
  {
    "Path": "/",
    "UserName": "user1",
    "UserId": "xxxxxxxx",
    "Arn": "arn:aws:iam::accountid:user/user1",
    "CreateDate": "2014-01-15T19:57:30+00:00",
    "c7n:matched-keys": [
      {
        "active": true,
        "last_rotated": "2014-01-15T19:57:30+00:00",
        "last_used_date": "2020-04-10T20:18:00+00:00",
        "last_used_region": "us-west-2",
        "last_used_service": "sqs",
        "c7n:match-type": "credential"
      }
    ],
    "c7n:credential-report": {
      "user": "user1",
      "arn": "arn:aws:iam::accountid:user/user1",
      "user_creation_time": "2014-01-15T19:57:30+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-04-09T17:35:30+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null
        },
        {
          "active": true,
          "last_rotated": "2014-01-15T19:57:30+00:00",
          "last_used_date": "2020-04-10T20:18:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "sqs",
          "c7n:match-type": "credential"
        }
      ]
    }
  }
]
```

**Comment by kapilt** [comment]
thanks for the copious logs, one ask would be you try trunk there were two fixes from @zscholl  on this, if your just on one you might be getting them both, the use case sounded similar, if its still an issue happy to dive deeper and the context here is helpful, thanks.

**Comment by zscholl** [comment]
@yufuluo #5535 should fix the issue you're experiencing #5551 fixed a tangential but  unrelated bug.

Please try using master and see if that fixes your issue.

**Comment by yufuluo** [comment]
@zscholl  and @kapilt thanks for all the hard work and help!!
I've tried the above changes with different filter orders, and that seems to work! None of the keys are marked as matched keys now!
However, the above 3 IAM users are still counted as the resources should be taken action (shown as below, `"c7n:matched-keys": []`, so no key will be disabled, but since we also send notifications to resource owners so this may lead to false alarm)

```
[
  {
    "Path": "/",
    "UserName": "user1",
    "UserId": "xxxxxxx",
    "Arn": "arn:aws:iam::<accountid>:user/user1",
    "CreateDate": "2014-01-15T19:57:30+00:00",
    "c7n:matched-keys": [],
    "c7n:credential-report": {
      "user": "user1",
      "arn": "arn:aws:iam::<accountid>:user/user1",
      "user_creation_time": "2014-01-15T19:57:30+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-04-09T17:35:30+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        },
        {
          "active": true,
          "last_rotated": "2014-01-15T19:57:30+00:00",
          "last_used_date": "2020-04-12T01:28:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "sqs"
        }
      ]
    }
  },
  {
    "Path": "/",
    "UserName": "user3",
    "UserId": "xxxxxxx",
    "Arn": "arn:aws:iam::<accountid>:user/user3",
    "CreateDate": "2018-12-17T17:50:00+00:00",
    "PasswordLastUsed": "2020-04-10T13:29:15+00:00",
    "c7n:matched-keys": [],
    "c7n:credential-report": {
      "user": "user3",
      "arn": "arn:aws:iam::<accountid>:user/user3",
      "user_creation_time": "2018-12-17T17:50:00+00:00",
      "password_enabled": true,
      "password_last_used": "2020-04-10T13:29:15+00:00",
      "password_last_changed": "2018-12-18T18:18:37+00:00",
      "password_next_rotation": null,
      "mfa_active": true,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2019-01-31T23:17:36+00:00",
          "last_used_date": "2020-03-18T17:31:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "ec2"
        },
        {
          "active": false,
          "last_rotated": "2018-12-17T17:50:01+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        }
      ]
    }
  },
  {
    "Path": "/",
    "UserName": "user2",
    "UserId": "xxxxxxxx",
    "Arn": "arn:aws:iam::<accountid>:user/user2",
    "CreateDate": "2019-03-07T20:05:58+00:00",
    "PasswordLastUsed": "2020-04-10T12:16:46+00:00",
    "c7n:matched-keys": [],
    "c7n:credential-report": {
      "user": "user2",
      "arn": "arn:aws:iam::<accountid>:user/user2",
      "user_creation_time": "2019-03-07T20:05:58+00:00",
      "password_enabled": true,
      "password_last_used": "2020-04-10T12:16:46+00:00",
      "password_last_changed": "2020-01-29T17:47:45+00:00",
      "password_next_rotation": null,
      "mfa_active": true,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2020-01-29T17:56:27+00:00",
          "last_used_date": "2020-02-03T20:05:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "rds"
        },
        {
          "active": false,
          "last_rotated": "2019-03-07T20:05:59+00:00",
          "last_used_date": null,
          "last_used_region": null,
          "last_used_service": null,
          "c7n:match-type": "credential"
        }
      ]
    }
  }
]
```

**Comment by afarhadi-life360** [comment]
Yeah I think this is still happening

This is my policy
```
  - name: iam-deactivate-old-keys
    resource: iam-user
    filters:
      - and:
        - type: credential
          key: access_keys.active
          value: true
          op: eq
        - type: credential
          key: access_keys.last_rotated
          value_type: age
          value: 30
          op: greater-than
        - type: credential
          key: access_keys.last_used_date
          value_type: age
          value: 99
          op: greater-than
```

For example, this one is being matched for my action.  Neither of these keys should be matched since they don't meet all the criteria.  Using 0.9.18.0


```
    "c7n:credential-report": {
      "user": "xxx",
      "arn": "arn:aws:iam::xxx:user/xxx",
      "user_creation_time": "2019-03-27T18:19:48+00:00",
      "password_enabled": true,
      "password_last_used": "2022-09-06T21:08:14+00:00",
      "password_last_changed": "2022-06-21T23:12:27+00:00",
      "password_next_rotation": "2024-06-20T23:12:27+00:00",
      "mfa_active": true,
      "access_keys": [
        {
          "active": false,
          "last_rotated": "2019-03-27T18:19:50+00:00",
          "last_used_date": "2021-04-26T18:00:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "ecr",
          "c7n:match-type": "credential"
        },
        {
          "active": true,
          "last_rotated": "2021-04-26T22:52:49+00:00",
          "last_used_date": "2022-09-14T21:30:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "ecr",
          "c7n:match-type": "credential"
        }
      ]
    }
```

**Comment by andersonfelixs** [comment]
Guys, do we have any updates on this case?

**Comment by ilepow34** [comment]
I was able to work around this by filtering on the length of `c7n:matched-keys`

For example:

```
filters:
  - type: credential
    key: access_keys.active
    value: true
    op: eq
  - type: credential
    key: access_keys.last_used_date
    value: 90
    op: gt
  - type: value
    key: length("c7n:matched-keys")
    value: 1
    op: gte
```

**Comment by jare19** [comment]
> - type: value
>     key: length("c7n:matched-keys")
>     value: 1
>     op: gte

This worked for me as well thanks @ilepow34

**Comment by nitrocode** [comment]
I ran into this bug today and it wreaked some havoc on our system.

Basically if there were multiple keys, if one of the keys matched, it would deactivate all of the keys, and then it would delete all of the keys, and of course, aws iam access keys cannot be restored. Luckily we were able to mitigate this a little because of our rollout process but this gives us less trust in the filters/actions in the system.

---

I had this `iam-deactivate-old-keys` policy searching for keys that haven't been used for 330 days and it was running correctly with multiple keys (as per the above workaround). I also had a `iam-delete-old-keys` which was a copy of this policy (using the same workaround) except it looked for disabled keys that are over 1000 days unused..

<details><summary>iam-deactivate-old-keys</summary>

```yaml
policies:
  - name: iam-deactivate-old-keys
    resource: iam-user
    tags:
      - schedule:daily
    description: |
      Disable IAM keys that haven't been used in the last 330 days.
    conditions:
      - region: us-east-1
    filters:
      - type: credential
        key: access_keys.active
        value: true
        op: eq
      - or:
        - type: credential
          key: access_keys.last_used_date
          value_type: age
          value: 330
          op: greater-than
        - type: credential
          key: access_keys.last_used_date
          value: absent
      # Workaround in https://github.com/cloud-custodian/cloud-custodian/issues/5583#issuecomment-1603010775
      - type: value
        key: length("c7n:matched-keys")
        value: 1
        op: gte
      - type: value
        key: "\"c7n:matched-keys\"[0].active"
        value: true
        op: eq
      - or:
        - type: value
          key: "\"c7n:matched-keys\"[0].last_used_date"
          value_type: age
          value: 330
          op: greater-than
        - type: value
          key: "\"c7n:matched-keys\"[0].last_used_date"
          value: absent
    actions:
      # RECOMMEND replacing this action with a slack notification instead of disabling
      - type: remove-keys
        matched: true
        disable: true
```

</details>

<details><summary>iam-delete-old-keys</summary>

```yaml
  - name: iam-delete-old-keys
    resource: iam-user
    description: |
      Delete IAM keys that haven't been used for a long time.
    conditions:
      - region: us-east-1
    filters:
      - type: credential
        key: access_keys.active
        value: false
        op: eq
      - or:
        - type: credential
          key: access_keys.last_used_date
          value_type: age
          value: 1000
          op: greater-than
        - type: credential
          key: access_keys.last_used_date
          value: absent
      # Workaround in https://github.com/cloud-custodian/cloud-custodian/issues/5583#issuecomment-1603010775
      - type: value
        key: length("c7n:matched-keys")
        value: 1
        op: gte
      - type: value
        key: "\"c7n:matched-keys\"[0].active"
        value: false
        op: eq
      - or:
        - type: value
          key: "\"c7n:matched-keys\"[0].last_used_date"
          value_type: age
          value: 1000
          op: greater-than
        - type: value
          key: "\"c7n:matched-keys\"[0].last_used_date"
          value: absent
    actions:
      - type: remove-keys
        matched: true
        disable: false
```

</details>

I made the following change to both

<details><summary>diff</summary>

```diff
    filters:
      - type: credential
        key: access_keys.active
        value: true
        op: eq
+      - or:
        - type: credential
          key: access_keys.last_used_date
          value_type: age
          value: 330
          op: greater-than
+        - type: credential
+          key: access_keys.last_used_date
+          value: absent
+      - or:
        - type: value
          key: "\"c7n:matched-keys\"[0].last_used_date"
          value_type: age
          value: 330
          op: greater-than
+        - type: value
+          key: "\"c7n:matched-keys\"[0].last_used_date"
+          value: absent
```

</details>

The dry run showed that we had 20 or so resources affected by both policies. I audited each one and merged the PR. Then custodian resulted in far more resources affected than the ones matched.

Please prioritize this issue higher on the list. The bug should be fixed or documentation should be added to avoid using the `remove-keys` action for `aws.iam-user`.

---

Going forward we have decided to implement a better rollout.

1. Create a new policy with a filter and only a notify to slack action
    1. Check the output of the slack action if it results in the same number of resources impacted as the dry-run
1. Introduce an action and modify the policy so it targets a single account in a PR
    1. clickops the actions manually
    1. rerun the dry-run so it shows 0 resources to remediate
    1. if non-zero, then repeat from the clickops step
1. Roll it out to more accounts
    1. Follow the same steps above
1. Roll it out to all accounts
    1. Follow the same steps above
